#! /usr/bin/env gawk -f

BEGIN {
    a = 0
}

/^[^(]/ {
    a += 1
}

/^@12345/ {
    a -= 1
}

/^@1230/ {
    a -= 1
}

/^@23456/ {
    a -= 1
}

/^@2340/ {
    a -= 1
}

END {
    print "cmds: " a
}

