all: scratch

scratch: scratch/
	./run.sh scratch/FibonacciElement

BasicLoop:
	./run.sh ProgramFlow/BasicLoop

FibonacciSeries:
	./run.sh ProgramFlow/FibonacciSeries --no-bootstrap
 
SimpleFunction:
	./run.sh FunctionCalls/SimpleFunction

FibonacciElement:
	./run.sh FunctionCalls/FibonacciElement

StaticsTest:
	./run.sh FunctionCalls/StaticsTest

