all: SimpleFunction

scratch:
	./VMtranslator.py scratch.vm

BasicLoop:
	./run.sh ProgramFlow/BasicLoop

FibonacciSeries:
	./run.sh ProgramFlow/FibonacciSeries
 
SimpleFunction:
	./run.sh FunctionCalls/SimpleFunction

FibonacciElement:
	./run.sh FunctionCalls/FibonacciElement

